### PR TITLE
labels and references

### PR DESCRIPTION
**Pull request by grauschnabel**
Hi there, according to issue #5 i wrote the patch myself.  Please tell me if you release this, this should not affect the actual behavior.  If you don't want to release this, i would like to release it with a new name, because I really need this feature.

- Martin

### CODE REVIEW

**Comment by paulrobertlloyd** [comment]
Hi @grauschnabel, this is a very interesting and intriguing feature! I do have a few comments/suggestions before accepting your PR however.

1. Might it make sense to turn on numbering based on a global config/frontmatter setting, rather than assume the addition of a label should enable this feature? Apologies if I’ve misunderstood this functionality.
2. I wonder if using `id` rather than `label` is a better choice, given that this value translates to adding an `id` attribute to the figure?

Finally, it would be nice to maintain test coverage as new features are added. Would you be able to include these with your PR? Let me know if you need help adding them… although it’s been a long time since I wrote this plugin, so may need a refresher myself!

Thanks again,

Paul

**Comment by grauschnabel** [comment]
Hi @paulrobertlloyd, I try to explain my thoughts, for the decision I made. First of all, I try to make good pdfs using latex out of the jekyll posts.  So this is the perspective I look at this. Latex uses floating figure environments, and I try jekyll-figure to make it adjust so it behaves more than latex would do.  

1. I thought about this option. The behaviour of turned on labels is default for latex. Or better, its hard to turn it off, because if you have a figure then you want to reference to it in the text. I do not understand the html way without a reference to it. So yes, we could (easily) set it as global/frontmatter too.  But if there is a label and a reference, we can not say "no" to the numbering, otherwise a reference would have no label.

I use this adjustments in my (jekyll-latex-pdf)[https://gitlab.com/grauschnabel/jekyll-latex-pdf] package. 

2. In latex we have \label{somename} and \ref{somename} where the label is set inside the figure environment to make the compiler know where we want to reference to. This is counted in the order the label is set.  There is also \pageref{somename}, which does not make sense in html context, so the `{::nomarkdown type="latex"}See page \pageref{somename}{:/}` would do the job, thats why i just added the `figref` tag and  no `figpageref` tag.
I also find *label* more intuitiv for non html programmers, who just write their text in markdown, *id* is more a technical term.  Thats why, but I'm open to change this.

3. Tests would be nice, there I could learn from you.  I didn't use this much, but if I understand this, I would add it to *jekyll-latex-pdf* too.

So what do you think?

Martin

**Comment by paulrobertlloyd** [comment]
Thanks for the additional content @grauschnabel. It’s really helpful to know that some of these decisions are based upon prior art, which is always a good indicator. Let me noodle on this; hopefully I’ll have some time to devote to merging this feature in.

**Comment by jlconlin** [comment]
Why wasn't this merged in?

**Comment by paulrobertlloyd** [comment]
@jlconlin I don’t use Jekyll anymore, and this project is not a high priority. Feel free to fork the project and release your own version if you so wish.

**Pull request closed without merging**
